get:
  summary: List All Log Settings
  description: This endpoint retrieves log settings.
  operationId: listLogSettings
  tags:
    - Log Settings
    - Administration
  responses:
    '200':
      description: Log Settings
      content:
        application/json:
          schema:
            type: object
            properties:
              logSettings:
                $ref: ../components/schemas/logSettings.yaml
          examples:
            Log Settings Response:
              value:
                $ref: ../components/examples/logSettings.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
put:
  summary: Update Log Settings
  description: Update Log Settings
  operationId: updateLogSettings
  tags:
    - Administration
    - Log Settings
  requestBody:
    content:
      application/json:
        schema:
            type: object
            properties:
              logSettings:
                $ref: ../components/schemas/logSettings.yaml
  responses:
    '200':
      description: Update Log Settings Object
      content:
        application/json:
          schema:
            allOf:
              - $ref: ../components/schemas/user.yaml
              - $ref: ../components/schemas/200-success.yaml
          examples:
            Update User Response:
              value:
                $ref: ../components/examples/userSuccess.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml