put:
  summary: Toggle Active State of Environment
  description: Toggle Active State of Environment. Default is to toggle the current value.
  operationId: updateEnvironmentsActive
  tags:
    - Environments
  parameters:
  - $ref: ../components/parameters/id-path.yaml
  - $ref: ../components/parameters/active.yaml
  responses:
    '200':
      description: Environment Object
      content:
        application/json:
          schema:
            allOf:
            - type: object
              properties:
                environment:
                  $ref: ../components/schemas/environment.yaml
            - $ref: ../components/schemas/200-success.yaml
          examples:
            Update Environment Response:
              value:
                $ref: ../components/examples/environmentSuccess.json
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml