get:
  summary: Get Morpheus OpenAPI (Swagger) document as YAML.
  description: >-
    Get Morpheus OpenAPI (Swagger) document as YAML. This is the same document
    that you are reading at this very moment.
  operationId: docOpenapiYaml
  tags:
    - Documentation
  security: []
  responses:
    '200':
      description: OpenAPI YAML specification for the Morpheus API
      content:
        text/yaml:
          examples:
            yamlExample:
              summary: OpenApi (Swagger) YAML
              value:
                openapi: 3.1.0
                info: 
                  title: Morpheus API
                  description: Welcome ...
    '400':
      $ref: ../components/responses/400.yaml
    '401':
      $ref: ../components/responses/401.yaml
    '403':
      $ref: ../components/responses/403.yaml
    '404':
      $ref: ../components/responses/404.yaml
    '405':
      $ref: ../components/responses/405.yaml
    '406':
      $ref: ../components/responses/406.yaml
    '410':
      $ref: ../components/responses/410.yaml
    '429':
      $ref: ../components/responses/429.yaml
    '500':
      $ref: ../components/responses/500.yaml
    '503':
      $ref: ../components/responses/503.yaml
