get:
  summary: Get Morpheus OpenAPI (Swagger) document as JSON.
  description: >-
    Get Morpheus OpenAPI (Swagger) document as JSON. This is the same document
    that you are reading at this very moment.
  operationId: docOpenapi
  tags:
    - Documentation
  security: []
  responses:
    '200':
      description: OpenAPI JSON specification for the Morpheus API
      content:
        application/json:
          examples:
            jsonExample:
              summary: OpenAPI (Swagger) JSON
              value:
                openapi: 3.0.3
                info:
                  title: Morpheus API
                  description: Welcome ...
    '400':
      description: Bad Request.
    '401':
      description: Unauthorized.
    '403':
      description: Forbidden.
    '404':
      description: Object Not Found.
    '500':
      description: Internal Server Error.
    '503':
      description: Service Unavailable.
