get:
  tags:
    - Documentation
  summary: docOpenapi
  description: >-
    Get Morpheus OpenAPI (Swagger) document as JSON. This is the same document
    that you are reading at this very moment.
  operationId: docOpenapi
  parameters: []
  responses:
    '200':
      description: OpenAPI JSON specification for the Morpheus API
      headers: {}
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\ApiDocOpenapiResponse.yaml
          examples:
            jsonExample:
              summary: OpenAPI (Swagger) JSON
              value:
                openapi: 3.0.3
                info:
                  title: Morpheus API
                  description: Welcome ...
    '400':
      description: Bad Request.
      headers: {}
      content: {}
    '401':
      description: Unauthorized.
      headers: {}
      content: {}
    '403':
      description: Forbidden.
      headers: {}
      content: {}
    '404':
      description: Object Not Found.
      headers: {}
      content: {}
    '500':
      description: Internal Server Error.
      headers: {}
      content: {}
    '503':
      description: Service Unavailable.
      headers: {}
      content: {}
  deprecated: false
  security: []
parameters: []
