get:
  summary: Get Morpheus OpenAPI (Swagger) document as YAML.
  description: >-
    Get Morpheus OpenAPI (Swagger) document as YAML. This is the same document
    that you are reading at this very moment.
  operationId: docOpenapiYaml
  tags:
    - Documentation
  security: []
  responses:
    '200':
      description: OpenAPI YAML specification for the Morpheus API
      content:
        text/yaml:
          examples:
            yamlExample:
              summary: OpenApi (Swagger) YAML
              value:
                openapi: 3.1.0
                info: 
                  title: Morpheus API
                  description: Welcome ...
    '400':
      description: Bad Request.
    '401':
      description: Unauthorized.
    '403':
      description: Forbidden.
    '404':
      description: Object Not Found.
    '500':
      description: Internal Server Error.
    '503':
      description: Service Unavailable.
