type: object
properties:
  meta:
    type: object
    properties:
      offset:
        type: integer
        format: int64
        description: >-
          Offset records, the number of records to skip, can be used to paginate
          over results.
        default: 0
      max:
        type: integer
        format: int64
        description: Max size, the maximum number of records to include in the response.
        default: 25
      size:
        type: integer
        format: int64
        description: Number of records returned in the response
        default: 0
      total:
        type: integer
        format: int64
        description: Total number of records found
        default: 0