title: ApiDocOpenapiResponse
required:
  - openapi
  - info
type: object
properties:
  openapi:
    type: string
  info:
    type: object
examples:
  - openapi: 3.0.3
    info:
      title: Morpheus API
      description: Welcome ...
