type: object
properties: 
  id: 
    type: integer
    format: int64
  account: 
    type: object
    properties: 
      id: 
        type: integer
        format: int64
      name: 
        type: string
  code: 
    type: string
  name: 
    type: string
  description: 
    type: string
  visibility: 
    type: string
  active: 
    type: boolean
  sortOrder: 
    type: integer
    format: int64
  dateCreated: 
    type: string
    format: date-time
  lastUpdated: 
    type: string
    format: date-time